vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /csv/files
    #        upload_destination: '%kernel.project_dir%/public/csv/files'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
