vich_uploader:
    db_driver: orm

    mappings:
        csv_files:
            uri_prefix: /csv/files
            upload_destination: '%kernel.project_dir%/public/csv/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 3, dirs: 1 }
